runtime: php
vm: true

handlers:
- url: /
  script: index.php

- url: /index\.html
  script: index.php

- url: /(.*\.(gif|png|jpg|js))$
  static_files: \1
  upload: .+\.(gif|png|jpg)$
  application_readable: true

- url: /(.+\.php)$
  script: \1